using System;

public class Majors
{
	public Majors()
	{
        public Dictionary<string, string> majors =
        {
            {"Psychology", "Arts and Sciences"},
            {"Religion", "Arts and Sciences"},
            {"Sociology", "Arts and Sciences"},
            {"Womens and Gender Studies", "Arts and Sciences"},
            {"Biology", "Arts and Sciences"},
            {"Biotechnology", "Arts and Sciences"},
            {"Black Studies", "Arts and Sciences"},
            {"Chemistry", "Arts and Sciences"},
            {"Economics", "Arts and Sciences"},
            {"English", "Arts and Sciences"},
            {"Environmental Studies", "Arts and Sciences"},
            {"Foreign Language and Literature", "Arts and Sciences"},
            {"General Science", "Arts and Sciences"},
            {"Geography", "Arts and Sciences"},
            {"Geology", "Arts and Sciences"},
            {"History", "Arts and Sciences"}	,
            {"Interdisciplinary Studies", "Arts and Sciences"},	
            {"International Studies", "Arts and Sciences"},
            {"Latino/Latin American Studies", "Arts and Sciences"},
            {"Mathematics", "Arts and Sciences"},
            {"Neuroscience", "Arts and Sciences"},
            {"Philosophy", "Arts and Sciences"},
            {"Physics", "Arts and Sciences"},
            {"Political Science", "Arts and Sciences"},
            {"Business Administration", "Business Administration"},
            {"Speech Communication", "Communications, Fine Arts, and Media"},
            {"Studio Art", "Communications, Fine Arts, and Media"},
            {"Theatre", "Communications, Fine Arts, and Media"},
            {"Art History", "Communications, Fine Arts, and Media"},
            {"Broadcasting", "Communications, Fine Arts, and Media"},
            {"Creative Writing", "Communications, Fine Arts, and Media"},
            {"Journalism", "Communications, Fine Arts, and Media"},
            {"Music Education", "Communications, Fine Arts, and Media"},
            {"Music Performance", "Communications, Fine Arts, and Media"},
            {"Public Health", "Education"},
            {"Recreation and Leisure Studies", "Education"},
            {"Secondary Education", "Education"},
            {"Special Education", "Education"},
            {"Speech-Language Pathology", "Education"},
            {"Athletic Training", "Education"},
            {"Community Health", "Education"},
            {"Elementary Education", "Education"},
            {"Elementary Education, Special Education", "Education"},
            {"Library Science", "Education"},
            {"Physical Education", "Education"},
            {"Architectural Engineering", "Engineering"},
            {"Civil Engineering", "Engineering"},
            {"Computer Engineering", "Engineering"},
            {"Construction Engineering", "Engineering"},
            {"Construction Management", "Engineering"},
            {"Electronics Engineering", "Engineering"},
            {"Bioinformatics", "Information Science and Technology"},
            {"Computer Science", "Information Science and Technology"},
            {"Information Assurance", "Information Science and Technology"},
            {"IT Innovation", "Information Science and Technology"},
            {"Management Information Systems", "Information Science and Technology"},
            {"Social Work", "Public Affairs and Community Service"},
            {"Aviation", "Public Affairs and Community Service"},
            {"Criminology and Criminal Justice", "Public Affairs and Community Service"},
            {"Emergency Management", "Public Affairs and Community Service"},
            {"General Studies", "Public Affairs and Community Service"};
        }
	}
}
